enabled: true
headline: 'Support GCCA'
text:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Help make arts access possible.'
image: popup-2.jpg
button_text: 'Donate Now'
button_link: 'https://artcentergreenville.org/support/donate'
open_in_new_tab: true
show_on: homepage
trigger: immediately
hide_on_mobile: false
dismiss_duration: '7'
campaign_id: august-donate
