title: 'First Friday'
author: 916c3785-d212-40bc-89ff-572097ac9582
updated_by: af34862d-025c-48c9-ad41-5b60c3f113c3
updated_at: 1752247885
blueprint: event_category
content: 'Join GCCA for First Friday each month. Every month you can enjoy new gallery exhibitions, studio artists, performing arts series, demos, and more. It is free to attend and open to all ages. After you’ve visited, hop over to other open galleries and restaurants in the West Village or Downtown Greenville!'
