title: 'First Friday'
author: 916c3785-d212-40bc-89ff-572097ac9582
updated_by: 05d798de-8a18-4794-a3f7-7c07f56a8da9
updated_at: 1744558343
blueprint: event_category
content: 'Join GCCA for First Friday each month. Every month you can enjoy new gallery exhibitions, studio artists, performing arts series, demos, and more. It is free to attend and open to all ages. After you’ve visited, hop over to other open galleries and restaurants in the West Village or Downtown Greenville!'
